-- 0001_init.sql — Initial database schema.
-- Creates the two core tables needed for the portfolio backend.
-- Run with: npx wrangler d1 migrations apply portfolio-db [--local | --remote]

-- Stores contact form submissions from the public-facing contact form.
-- Status field allows admin moderation: pending → read → archived.
CREATE TABLE IF NOT EXISTS submissions (
    id TEXT PRIMARY KEY,               -- UUID generated by crypto.randomUUID() in the API
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'pending',     -- Moderation state: 'pending', 'read', or 'archived'
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Stores active admin session tokens created by /api/login.
-- Tokens are deleted on logout (/api/logout) for server-side invalidation.
CREATE TABLE IF NOT EXISTS admin_sessions (
    token TEXT PRIMARY KEY,            -- High-entropy token: two UUIDs concatenated
    expires_at DATETIME NOT NULL       -- 2 hours from creation time
);
